################################################################
# STEP 2: build a small image and run crusoe-cloud-controller-manager binary #
################################################################
FROM alpine:3.20.3

COPY crusoe-cloud-controller-manager /usr/local/go/bin/crusoe-cloud-controller-manager

ENTRYPOINT ["/usr/local/go/bin/crusoe-cloud-controller-manager"]