// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package mock_sdn is a generated GoMock package.
package mock_sdn

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	sdn "github.com/crusoecloud/crusoe-cloud-controller-manager/internal/routes/sdn"
)

// MockPodCIDRAllocationClient is a mock of PodCIDRAllocationClient interface.
type MockPodCIDRAllocationClient struct {
	ctrl     *gomock.Controller
	recorder *MockPodCIDRAllocationClientMockRecorder
}

// MockPodCIDRAllocationClientMockRecorder is the mock recorder for MockPodCIDRAllocationClient.
type MockPodCIDRAllocationClientMockRecorder struct {
	mock *MockPodCIDRAllocationClient
}

// NewMockPodCIDRAllocationClient creates a new mock instance.
func NewMockPodCIDRAllocationClient(ctrl *gomock.Controller) *MockPodCIDRAllocationClient {
	mock := &MockPodCIDRAllocationClient{ctrl: ctrl}
	mock.recorder = &MockPodCIDRAllocationClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPodCIDRAllocationClient) EXPECT() *MockPodCIDRAllocationClientMockRecorder {
	return m.recorder
}

// CreatePodCIDRAllocations mocks base method.
func (m *MockPodCIDRAllocationClient) CreatePodCIDRAllocations(ctx context.Context, req sdn.CreatePodCIDRAllocationsRequest) (*sdn.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePodCIDRAllocations", ctx, req)
	ret0, _ := ret[0].(*sdn.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePodCIDRAllocations indicates an expected call of CreatePodCIDRAllocations.
func (mr *MockPodCIDRAllocationClientMockRecorder) CreatePodCIDRAllocations(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePodCIDRAllocations", reflect.TypeOf((*MockPodCIDRAllocationClient)(nil).CreatePodCIDRAllocations), ctx, req)
}

// DeletePodCIDRAllocations mocks base method.
func (m *MockPodCIDRAllocationClient) DeletePodCIDRAllocations(ctx context.Context, req sdn.DeletePodCIDRAllocationsRequest) (*sdn.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePodCIDRAllocations", ctx, req)
	ret0, _ := ret[0].(*sdn.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePodCIDRAllocations indicates an expected call of DeletePodCIDRAllocations.
func (mr *MockPodCIDRAllocationClientMockRecorder) DeletePodCIDRAllocations(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePodCIDRAllocations", reflect.TypeOf((*MockPodCIDRAllocationClient)(nil).DeletePodCIDRAllocations), ctx, req)
}

// ListPodCIDRAllocationOperations mocks base method.
func (m *MockPodCIDRAllocationClient) ListPodCIDRAllocationOperations(ctx context.Context, q sdn.ListPodCIDRAllocationOperationsQuery) ([]sdn.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPodCIDRAllocationOperations", ctx, q)
	ret0, _ := ret[0].([]sdn.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPodCIDRAllocationOperations indicates an expected call of ListPodCIDRAllocationOperations.
func (mr *MockPodCIDRAllocationClientMockRecorder) ListPodCIDRAllocationOperations(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPodCIDRAllocationOperations", reflect.TypeOf((*MockPodCIDRAllocationClient)(nil).ListPodCIDRAllocationOperations), ctx, q)
}

// ListVPCPrefixReservations mocks base method.
func (m *MockPodCIDRAllocationClient) ListVPCPrefixReservations(ctx context.Context, ids []string) ([]sdn.VPCPrefixReservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVPCPrefixReservations", ctx, ids)
	ret0, _ := ret[0].([]sdn.VPCPrefixReservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVPCPrefixReservations indicates an expected call of ListVPCPrefixReservations.
func (mr *MockPodCIDRAllocationClientMockRecorder) ListVPCPrefixReservations(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVPCPrefixReservations", reflect.TypeOf((*MockPodCIDRAllocationClient)(nil).ListVPCPrefixReservations), ctx, ids)
}

// ListPodCIDRAllocations mocks base method.
func (m *MockPodCIDRAllocationClient) ListPodCIDRAllocations(ctx context.Context, q sdn.ListPodCIDRAllocationsQuery) ([]sdn.PodCIDRAllocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPodCIDRAllocations", ctx, q)
	ret0, _ := ret[0].([]sdn.PodCIDRAllocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPodCIDRAllocations indicates an expected call of ListPodCIDRAllocations.
func (mr *MockPodCIDRAllocationClientMockRecorder) ListPodCIDRAllocations(ctx, q interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPodCIDRAllocations", reflect.TypeOf((*MockPodCIDRAllocationClient)(nil).ListPodCIDRAllocations), ctx, q)
}
